#.travis.yml
language: android

jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-30.0.3
    - android-30
    - extra-android-m2repository

branches:
  only:
    - pre_production

install:
  - chmod +x ./gradlew

script:
  - ./gradlew clean assembleDebug