#.travis.yml
language: android

jdk: oraclejdk8

android:
  components:
    - build-tools-30.0.3
    - android-30
    - platform-tools
    - tools
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
branches:
  only:
    - pre_production

install:
  - chmod +x ./gradlew

script:
  - ./gradlew clean assembleDebug